name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter 3.24.5
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'
          channel: 'stable'

      - name: Rebuild Clean Android Skeleton
        run: |
          mkdir temp_app
          cd temp_app
          flutter create --org com.example --project-name offline_walkie_chat . --platforms=android
          cp -r android ../
          cd ..
          rm -rf temp_app

      - name: Set SDK Versions
        run: |
          find android/ -name "build.gradle" -exec sed -i 's/minSdkVersion .*/minSdkVersion = 23/g' {} +
          find android/ -name "build.gradle" -exec sed -i 's/minSdkVersion flutter.minSdkVersion/minSdkVersion 23/g' {} +

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release --no-shrink

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: offline-walkie-app
          path: build/app/outputs/flutter-apk/*.apk
          
